# Site
name: 'OPENSL'
description: 'Tech Blog where people talk about cutting edge Techs'
meta_description: 'Tech Blog where people talk about cutting edge Techs.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-87463733-1'
disqus: 'nadunsblog'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  nadun:
    name: Nadun
    display_name: Nadun Indunil
    gravatar: 34087a5808a93ea9835e62515433880d
    email: nadun1indunil@gmail.com
    web: http://nadunindunil.github.io
    twitter: https://twitter.com/nadmatrix
    description: 'AWS Certified Solution Architect | Blogger | Developer | Engineer at Sysco Labs.'
  john:
    name: Maheshi
    display_name: Maheshi Gunrathne
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: maheshi.gunarathne1994@gmail.com
    web: https://www.linkedin.com/in/maheshi-gunarathne-861068131/?originalSubdomain=lk
    twitter: https://www.linkedin.com/in/maheshi-gunarathne-861068131/?originalSubdomain=lk
    description: 'Tech Evangelist | Engineer at 99X Technology.'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
